CFLAGS = -pthread -std=c++11 -lglfw3 -lGL -lGLU -lX11 -lXxf86vm -lXrandr -lpthread -lXi
BINDIR = bin
TARGET = $(BINDIR)/artificial-life-simulator.o
TEST_TARGET = $(BINDIR)/test.o
SRCDIR = src
TESTDIR = test
LIBDIR = lib
SRCEXT = cpp
BUILDDIR = build
INC = -I include